# Generated by Django 3.1.1 on 2020-10-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kayttajat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etunimi', models.CharField(max_length=30)),
                ('sukunimi', models.CharField(max_length=30)),
                ('kayttaja_nimi', models.CharField(max_length=30)),
                ('salasana', models.CharField(max_length=30)),
                ('sahkoposti', models.CharField(max_length=30)),
                ('last_update', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Osoite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField()),
                ('kaupunki', models.CharField(max_length=30)),
                ('osoite', models.CharField(max_length=30)),
                ('postinumero', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Toimipiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField()),
                ('toimipiste_nimi', models.CharField(max_length=30)),
                ('FK_osoite_id', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='palaute.osoite')),
            ],
        ),
        migrations.CreateModel(
            name='Palaute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palaute_pvm', models.DateField()),
                ('arvosana', models.PositiveIntegerField()),
                ('hyvaa', models.TextField()),
                ('huonoa', models.TextField()),
                ('parannettavaa', models.TextField()),
                ('FK_kayttaja_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='palaute.kayttajat')),
                ('FK_toimipiste_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='palaute.toimipiste')),
            ],
        ),
        migrations.AddField(
            model_name='kayttajat',
            name='FK_osoite_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='palaute.osoite'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palaute.question')),
            ],
        ),
    ]
