# Generated by Django 3.1.1 on 2020-10-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palaute', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palaute',
            name='FK_kayttaja_id',
        ),
    ]
