# Generated by Django 3.1.1 on 2020-10-01 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palaute', '0002_auto_20200925_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaupunki',
            fields=[
                ('kaupunki_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_update', models.DateField()),
                ('kaupunki', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='kayttajat',
            old_name='osoite_id',
            new_name='FK_osoite_id',
        ),
        migrations.RenameField(
            model_name='palaute',
            old_name='kayttaja_id',
            new_name='FK_kayttaja_id',
        ),
        migrations.RenameField(
            model_name='palaute',
            old_name='toimipiste_id',
            new_name='FK_toimipiste_id',
        ),
        migrations.RenameField(
            model_name='palaute',
            old_name='palaute_pvm',
            new_name='last_update',
        ),
        migrations.RenameField(
            model_name='toimipiste',
            old_name='osoite_id',
            new_name='FK_osoite_id',
        ),
        migrations.RemoveField(
            model_name='kayttajat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='osoite',
            name='id',
        ),
        migrations.RemoveField(
            model_name='palaute',
            name='id',
        ),
        migrations.RemoveField(
            model_name='toimipiste',
            name='id',
        ),
        migrations.AddField(
            model_name='kayttajat',
            name='kayttaja_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='osoite',
            name='kaupunki',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='osoite',
            name='last_update',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='osoite',
            name='osoite',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='osoite',
            name='osoite_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='osoite',
            name='postinumero',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palaute',
            name='palaute_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toimipiste',
            name='toimipiste_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='osoite',
            name='FK_kaupunki_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='palaute.kaupunki'),
            preserve_default=False,
        ),
    ]
