# Generated by Django 3.1.1 on 2020-10-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palaute', '0003_auto_20201001_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palaute',
            old_name='last_update',
            new_name='palaute_pvm',
        ),
    ]
